provider:
  host: https://localhost:9443 #Change the host

client:
  client-id: oQhUu3oqr_vCb_rsLB4ei0EbkBMa #Change client-id
  client-secret: jJVhIaRf9i8ogj_EEJfr5dh_EaZcHpX0gDNfffrNCtca # Change client-secret
  post-logout-uri: http://localhost:8080/NMLS/login
  scope: openid,internal_login,internal_user_mgt_view,internal_user_mgt_list,notification_info,profile,email
  authorization-grant-type: authorization_code


#No need to change the following configurations
spring:
  security:
    oauth2:
      client:
        registration:
          wso2:
            client-name : WSO2 Identity Server
            client-id: ${client.client-id} #Change client-id
            client-secret: ${client.client-secret} # Change client-secret
            authorization-grant-type: ${client.authorization-grant-type}
            scope: ${client.scope}
        provider:
          wso2:
            issuer-uri: ${provider.host}/oauth2/token

  thymeleaf:
    cache: false
